import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from '@/components/NavigationBar';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <NavigationBar />
    <html lang="en">
<<<<<<< HEAD
      
=======
   
>>>>>>> c8297b8d80fe5a827b561eefaf25595e21e4bd63
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
<<<<<<< HEAD
      
=======
    
>>>>>>> c8297b8d80fe5a827b561eefaf25595e21e4bd63
    </html>
    <Footer />
    </>
  );
}
